site_name: How to Dev

nav:
  - Home: index.md
  - Git and GitHub: git.md
  - Python:
    - Venv: venv.md

theme:
  name: material
  palette:
    scheme: slate  # dark mode as default
    primary: deep orange
    accent: amber

markdown_extensions:
- codehilite
- admonition

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kaiosod
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/kaiosod